// Do not edit. This file is machine generated by the Resource DLL Wizard.

library projectKursach;

{ITE} {DFMFileType} {kursach.dfm}
{ITE} {RCFileType} {Win32\Debug\projectKursach_DRC.rc}

{$R 'kursach.dfm' 'Form3:TForm'}
{$R 'Win32\Debug\projectKursach_DRC.res' 'Win32\Debug\projectKursach_DRC.rc'}

{$E ENU}

begin
end.
